### ISSUE TITLE
Sucking the joy out of blockudoku

### ISSUE THREAD

**Issue by JohnDelisle** [gary-z/blockudoku-ai#2]
So just wanted to share some feedback. 

It seems something/someone is generating AI blockudoku players, with formulaic names in an “AdjectiveAnimal” pattern, e.g. “CuriousBeaver”.  I can’t conclusively say it’s your bot/code, but the timing of your pushes aligns with my observation of the appearance of AI bots. 

Simply put, this has sucked all the joy from playing blockudoku. Sure, it’s just a silly little game, but a lot of people have found joy in playing it, both solo and vs other humans, particularly during covid. This AI is joyless to play against. Losing to the AI results in heavy penalties, and winning results in very little benefit, resulting in losing hard-earned player ranking. 

I’d like to encourage you to not ruin this game, and to apply your obvious talent to something less harmful to people looking for a simple pleasure like blockudoku.

**Comment by John-Yu** [comment]
Technology is technology.

**Comment by gary-z** [comment]
Hey, just saw your comment now.

Sorry you had that experience. I didn't even know there existed competition.

My code as is doesn't have the ability to play a game for you. The AI only plays it's own pretend game. Someone may have forked a version they can use to cheat. That said, even a very basic ai anyone with coding skills can write in an afternoon would easily beat human achievable scores. 

I still play the game on occasion even though I know I'd never be able to come close to what a machine can do. Let the cheaters do their thing. I think it's pretty sad someone is going back and forth inputting moves into a program. I imagine they got tired of doing it.
